steps:
  # Step #0: install dependencies and build
  - name: node
    id: 'install dependencies and build'
    entrypoint: sh
    args:
      - '-c'
      - |
        yarn install
        yarn build
    waitFor: ['-']

  # Step #1: deploy
  - name: tbcloud/docker-firebase
    id: 'deploy'
    args:
      - '-c'
      - |
        firebase deploy
